### ISSUE TITLE
Broken on Most Recent MCEdit Version - Here's the Fix

### ISSUE THREAD

**Issue by Avantir-Chaosfire** [Podshot/MCEdit-Filters#7]
For the most recent version of MCEdit, range maximums need to be incremented by 1. So lines 27 and 28 need to be

rangeX = range(x-1,x+2)
rangeZ = range(z-1,z+2)

and line 73 needs to be

yrange = range(y-length-random.randint(1,len_diversity),y + 1)

**Comment by tomsik68** [comment]
Could you please specify which filter this is related to?
